blank_issues_enabled: false
contact_links:
  - name: Best Practices Extension SF Community Support
    url: https://github.com/manvil95/BestPracticeExtensionSF/discussions
    about: Please ask and answer questions here.